{% set version = "2.18.0" %}

package:
  name: pagmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 5ad40bf3aa91857a808d6b632d9e1020341a33f1a4115d7a2b78b78fd063ae31

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make    # [unix]

outputs:
  - name: pagmo
    requirements:
      host:
        - eigen
        - nlopt     # [not arm64]
        - boost-cpp
        - tbb-devel
        - ipopt     # [x86]
      run:
        # NOTE: nlopt, tbb and ipopt
        # use run_exports().
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    files:
      - lib/libpagmo*{{ SHLIB_EXT }}   # [not win]
      - lib/libpagmo.so.*              # [linux]
      - lib/libpagmo.*.dylib           # [osx]
      - Library/bin/pagmo.dll          # [win]
    test:
      commands:
        - test -f $PREFIX/lib/libpagmo.so                                     # [linux]
        - test -f $PREFIX/lib/libpagmo.dylib                                  # [osx]
        - if not exist %PREFIX%\\Library\\bin\\pagmo.dll exit 1               # [win]

  - name: pagmo-devel
    build:
      run_exports:
        # NOTE: don't need to list tbb, as
        # the pagmo public headers do not
        # use tbb (thus, a dependee of pagmo
        # does not need to link to tbb).
        # pagmo's API and ABI change at minor rev bumps.
        - {{ pin_subpackage('pagmo', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
        - {{ pin_compatible('nlopt', max_pin='x.x') }}      # [not arm64]
        - {{ pin_compatible('ipopt', max_pin='x.x') }}      # [x86]
    requirements:
      host:
        - eigen
        - nlopt       # [not arm64]
        - boost-cpp
        - tbb-devel
        - ipopt       # [x86]
      run:
        - {{ pin_subpackage("pagmo", exact=True) }}
        - eigen
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
        - tbb-devel
    files:
      - include/pagmo            # [not win]
      - lib/cmake/pagmo          # [not win]
      - Library/include/pagmo    # [win]
      - Library/lib/pagmo.lib    # [win]
      - Library/lib/cmake/pagmo  # [win]
    test:
      commands:
        - test -f $PREFIX/include/pagmo/config.hpp                            # [unix]
        - if not exist %PREFIX%\\Library\\include\\pagmo\\config.hpp exit 1   # [win]
        - if not exist %PREFIX%\\Library\\lib\\pagmo.lib exit 1               # [win]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL-3.0-or-later OR LGPL-3.0-or-later
  license_file: COPYING.lgpl3
  summary: A C++ platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
